const languageFlags = {
  en: require('../../../assets/flags/uk-flag.png'),
  es: require('../../../assets/flags/spain-flag.png'),
  zh: require('../../../assets/flags/china-flag.png'),
  hi: require('../../../assets/flags/india-flag.png'),
  fr: require('../../../assets/flags/france-flag.png'),
  ko: require('../../../assets/flags/south-korea-flag.png'),
  ja: require('../../../assets/flags/japan-flag.png'),
  de: require('../../../assets/flags/germany-flag.png'),
  ar: require('../../../assets/flags/saudi-arabia-flag.png'),
  pt: require('../../../assets/flags/portugal-flag.png'),
  ru: require('../../../assets/flags/russia-flag.png'),
  it: require('../../../assets/flags/italy-flag.png'),
  tr: require('../../../assets/flags/turkey-flag.png'),     
  nl: require('../../../assets/flags/netherlands-flag.png'), 
  pl: require('../../../assets/flags/poland-flag.png'),     
  th: require('../../../assets/flags/thailand-flag.png'),   
  vi: require('../../../assets/flags/vietnam-flag.png'),   
  ms: require('../../../assets/flags/malaysia-flag.png'),   
  sv: require('../../../assets/flags/sweden-flag.png'),      
  no: require('../../../assets/flags/norway-flag.png'),     
  fi: require('../../../assets/flags/finland-flag.png'),   
  el: require('../../../assets/flags/greece-flag.png'),  
  hu: require('../../../assets/flags/hungary-flag.png'),  
  cs: require('../../../assets/flags/czech-republic-flag.png'), 
  ro: require('../../../assets/flags/romania-flag.png'),   
  da: require('../../../assets/flags/denmark-flag.png'),    
  he: require('../../../assets/flags/israel-flag.png'),   
  id: require('../../../assets/flags/indonesia-flag.png'),  
  uk: require('../../../assets/flags/ukraine-flag.png'),    
  fa: require('../../../assets/flags/iran-flag.png'),      
  bn: require('../../../assets/flags/bangladesh-flag.png')   
};

export default languageFlags;
