const languageFlags = {
  en: "/assets/flags/uk-flag.png",
  es: "/assets/flags/spain-flag.png",
  zh: "/assets/flags/china-flag.png",
  hi: "/assets/flags/india-flag.png",
  fr: "/assets/flags/france-flag.png",
  ko: "/assets/flags/south-korea-flag.png",
  ja: "/assets/flags/japan-flag.png",
  de: "/assets/flags/germany-flag.png",
  ar: "/assets/flags/saudi-arabia-flag.png",
  pt: "/assets/flags/portugal-flag.png",
  ru: "/assets/flags/russia-flag.png",
  it: "/assets/flags/italy-flag.png",
  tr: "/assets/flags/turkey-flag.png",     
  nl: "/assets/flags/netherlands-flag.png", 
  pl: "/assets/flags/poland-flag.png",     
  th: "/assets/flags/thailand-flag.png",   
  vi: "/assets/flags/vietnam-flag.png",   
  ms: "/assets/flags/malaysia-flag.png",   
  sv: "/assets/flags/sweden-flag.png",      
  no: "/assets/flags/norway-flag.png",     
  fi: "/assets/flags/finland-flag.png",   
  el: "/assets/flags/greece-flag.png",  
  hu: "/assets/flags/hungary-flag.png",  
  cs: "/assets/flags/czech-republic-flag.png", 
  ro: "/assets/flags/romania-flag.png",   
  da: "/assets/flags/denmark-flag.png",    
  he: "/assets/flags/israel-flag.png",   
  id: "/assets/flags/indonesia-flag.png",  
  uk: "/assets/flags/ukraine-flag.png",    
  fa: "/assets/flags/iran-flag.png",      
  bn: "/assets/flags/bangladesh-flag.png"
};

export default languageFlags;
