// src/constants/defaultSkills.js

export const defaultSkills = [
  { key: 'coding', color: '#D8315B' },
  { key: 'design', color: '#F2542D' },
  { key: 'writing', color: '#0A1045' },
  { key: 'communication', color: '#D8315B' },
  { key: 'management', color: '#F2542D' },
  { key: 'marketing', color: '#0A1045' },
  { key: 'public speaking', color: '#D8315B' },
  { key: 'photography', color: '#F2542D' },
  { key: 'video editing', color: '#0A1045' },
  { key: 'data analysis', color: '#D8315B' },
  { key: 'project management', color: '#F2542D' },
  { key: 'sales', color: '#0A1045' },
  { key: 'seo', color: '#D8315B' },
  { key: 'teaching', color: '#F2542D' },
  { key: 'networking', color: '#0A1045' },
  { key: 'teamwork', color: '#F2542D' },
  { key: 'time management', color: '#D8315B' },
  { key: 'problem solving', color: '#F2542D' },
  { key: 'creativity', color: '#0A1045' },
  { key: 'strategic planning', color: '#D8315B' },
  { key: 'leadership', color: '#F2542D' },
  { key: 'conflict resolution', color: '#0A1045' },
  { key: 'customer service', color: '#D8315B' },
  { key: 'event planning', color: '#F2542D' },
  { key: 'language proficiency', color: '#0A1045' },
  { key: 'financial analysis', color: '#D8315B' },
  { key: 'graphic design', color: '#F2542D' },
  { key: 'social media', color: '#0A1045' },
  { key: 'UX/UI design', color: '#D8315B' },
  { key: 'copywriting', color: '#F2542D' },
  { key: 'database management', color: '#0A1045' },
  { key: 'programming', color: '#D8315B' },
  { key: 'customer engagement', color: '#F2542D' },
  { key: 'logistics', color: '#0A1045' },
  { key: 'research', color: '#D8315B' },
  { key: 'quality control', color: '#F2542D' },
  { key: 'market research', color: '#0A1045' },
  { key: 'product management', color: '#D8315B' },
  { key: 'translation', color: '#F2542D' },
];
