const countryFlags = {
  "United Kingdom": "/assets/flags/uk-flag.png",
  "United States": "/assets/flags/usa-flag.png",
  "South Korea": "/assets/flags/south-korea-flag.png",
  "Japan": "/assets/flags/japan-flag.png",
  "Germany": "/assets/flags/germany-flag.png",
  "France": "/assets/flags/france-flag.png",
  "Canada": "/assets/flags/canada-flag.png",
  "Australia": "/assets/flags/australia-flag.png",
  "Spain": "/assets/flags/spain-flag.png",
  "China": "/assets/flags/china-flag.png",
  "Saudi Arabia": "/assets/flags/saudi-arabia-flag.png",
  "Poland": "/assets/flags/poland-flag.png",
  "Portugal": "/assets/flags/portugal-flag.png",
  "India": "/assets/flags/india-flag.png",
  "Russia": "/assets/flags/russia-flag.png",
  "Mexico": "/assets/flags/mexico-flag.png",
  "Netherlands": "/assets/flags/netherlands-flag.png",
  "Italy": "/assets/flags/italy-flag.png",
  "Turkey": "/assets/flags/turkey-flag.png",
  "Brazil": "/assets/flags/brazil-flag.png",
  "UAE": "/assets/flags/united-arab-emirates-flag.png",
  "Switzerland": "/assets/flags/switzerland-flag.png",
  "Denmark": "/assets/flags/denmark-flag.png",
  "Singapore": "/assets/flags/singapore-flag.png",
  "Romania": "/assets/flags/romania-flag.png",
  "Greece": "/assets/flags/greece-flag.png",
  "Belgium": "/assets/flags/belgium-flag.png",
  "Ukraine": "/assets/flags/ukraine-flag.png",
  "Vietnam": "/assets/flags/vietnam-flag.png",
  "Czech Republic": "/assets/flags/czech-republic-flag.png",
  "New Zealand": "/assets/flags/new-zealand-flag.png",
  "Norway": "/assets/flags/norway-flag.png",
  "Israel": "/assets/flags/israel-flag.png",
  "Sweden": "/assets/flags/sweden-flag.png",
  "Thailand": "/assets/flags/thailand-flag.png",
  "Hungary": "/assets/flags/hungary-flag.png",
  "Indonesia": "/assets/flags/indonesia-flag.png",
  "Austria": "/assets/flags/austria-flag.png",
  "Palestine": "/assets/flags/palestine-flag.png",
  "Finland": "/assets/flags/finland-flag.png",
  "Slovakia": "/assets/flags/slovakia-flag.png",
  "Pakistan": "/assets/flags/pakistan-flag.png",
  "Serbia": "/assets/flags/serbia-flag.png",
  "Egypt": "/assets/flags/egypt-flag.png",
  "Ireland": "/assets/flags/ireland-flag.png",
  "England": "/assets/flags/england-flag.png",
  "Chile": "/assets/flags/chile-flag.png",
  "Croatia": "/assets/flags/croatia-flag.png",
  "Argentina": "/assets/flags/argentina-flag.png",
  "South Africa": "/assets/flags/south-africa-flag.png",
  "Morocco": "/assets/flags/morocco-flag.png",
  "Georgia": "/assets/flags/georgia-flag.png",
  "Colombia": "/assets/flags/colombia-flag.png",
  "Qatar": "/assets/flags/qatar-flag.png",
  "Bulgaria": "/assets/flags/bulgaria-flag.png",
  "Albania": "/assets/flags/albania-flag.png",
  "Bangladesh": "/assets/flags/bangladesh-flag.png",
  "Philippines": "/assets/flags/philiphines-flag.png",
  "Scotland": "/assets/flags/scotland-flag.png",
  "Algeria": "/assets/flags/algeria-flag.png",
  "Azerbaijan": "/assets/flags/azerbaijan-flag.png",
  "Kazakhstan": "/assets/flags/kazakhstan-flag.png",
  "Lithuania": "/assets/flags/lithuania-flag.png",
  "Nigeria": "/assets/flags/nigeria-flag.png",
  "Estonia": "/assets/flags/estonia-flag.png",
  "Montenegro": "/assets/flags/montenegro-flag.png",
  "Peru": "/assets/flags/peru-flag.png",
  "Jamaica": "/assets/flags/jamaica-flag.png",
  "Malta": "/assets/flags/malta-flag.png",
  "Uruguay": "/assets/flags/uruguay-flag.png",
  "Iceland": "/assets/flags/iceland-flag.png",
  "Bahrain": "/assets/flags/bahrain-flag.png",
  "Luxembourg": "/assets/flags/luxembourg-flag.png",
  "Costa Rica": "/assets/flags/costa-rica-flag.png",
  "Puerto Rico": "/assets/flags/puerto-rico-flag.png",
  "Jordan": "/assets/flags/jordan-flag.png",
  "Kuwait": "/assets/flags/kuwait-flag.png",
  "Venezuela": "/assets/flags/venezuela-flag.png",
  "Ghana": "/assets/flags/ghana-flag.png",
  "Tunisia": "/assets/flags/tunusia-flag.png",
  "Nepal": "/assets/flags/nepal-flag.png",
  "Ivory Coast": "/assets/flags/ivory-coast-flag.png",
  "Macedonia": "/assets/flags/macedonia-flag.png",
  "Kyrgyzstan": "/assets/flags/kyrgyzstan-flag.png",
  "Uzbekistan": "/assets/flags/uzbekistan-flag.png",
  "Libya": "/assets/flags/libya-flag.png",
  "Bosnia": "/assets/flags/bosnia-flag.png",
  "Iran": "/assets/flags/iran-flag.png",
  "Kosovo": "/assets/flags/kosovo-flag.png",
  "Mongolia": "/assets/flags/mongolia-flag.png",
  "Syria": "/assets/flags/syria-flag.png",
  "Tanzania": "/assets/flags/tanzania-flag.png",
  "Malaysia": "/assets/flags/malaysia-flag.png",
  "Paraguay": "/assets/flags/paraguay-flag.png",
  "Monaco": "/assets/flags/monaco-flag.png",
  "Senegal": "/assets/flags/senegal-flag.png",
  "Somalia": "/assets/flags/somalia-flag.png",
  "Dominican Republic": "/assets/flags/dominican-republic-flag.png",
  "Cameroon": "/assets/flags/cameroon-flag.png",
  "Republic of Congo": "/assets/flags/republic-of-congo-flag.png",
  "Guatemala": "/assets/flags/guatemala-flag.png",
  "Sudan": "/assets/flags/sudan-flag.png",
  "Cuba": "/assets/flags/cuba-flag.png",
  "Tajikistan": "/assets/flags/tajikistan-flag.png",
  "Laos": "/assets/flags/laos-flag.png",
  "Honduras": "/assets/flags/honduras-flag.png",
  "Ethiopia": "/assets/flags/ethiopia-flag.png",
  "Yemen": "/assets/flags/yemen-flag.png",
  "Guinea": "/assets/flags/guinea-flag.png",
  "Slovenia": "/assets/flags/slovenia-flag.png", 
  "Burkina Faso": "/assets/flags/burkina-faso-flag.png",
  "Bahamas": "/assets/flags/bahamas-flag.png",
  "North Korea": "/assets/flags/north-korea-flag.png",
  "Turkmenistan": "/assets/flags/turkmenistan-flag.png",
  "Mauritius": "/assets/flags/mauritius-flag.png",
  "Gambia": "/assets/flags/gambia-flag.png",
  "Niger": "/assets/flags/niger-flag.png",
  "Trinidad and Tobago": "/assets/flags/trinidad-and-tobago-flag.png",
  "Sierra Leone": "/assets/flags/sierra-leone-flag.png",
  "Benin": "/assets/flags/benin-flag.png",
  "South Sudan": "/assets/flags/south-sudan-flag.png",
  "Togo": "/assets/flags/togo-flag.png",
  "Mauritania": "/assets/flags/mauritania-flag.png",
  "Madagascar": "/assets/flags/madagascar-flag.png",
  "Saint Vincent and the Grenadines": "/assets/flags/saint-vincent-and-the-grenadines-flag.png",
  "Suriname": "/assets/flags/suriname-flag.png",
  "Faroe Islands": "/assets/flags/faroe-islands-flag.png",
  "Greenland": "/assets/flags/greenland-flag.png",
  "Burundi": "/assets/flags/burundi-flag.png",
  "Guyana": "/assets/flags/guyana-flag.png",
  "French Guiana": "/assets/flags/french-guiana-flag.png",
  "Tonga": "/assets/flags/tonga-flag.png",
  "Central African Republic": "/assets/flags/central-african-republic-flag.png",
  "Djibouti": "/assets/flags/djibouti-flag.png"
};

export default countryFlags;
