const countryFlags = {
  "United Kingdom": require('assets/flags/uk-flag.png'),
  "United States": require('assets/flags/usa-flag.png'),
  "South Korea": require('assets/flags/south-korea-flag.png'),
  "Japan": require('assets/flags/japan-flag.png'),
  "Germany": require('assets/flags/germany-flag.png'),
  "France": require('assets/flags/france-flag.png'),
  "Canada": require('assets/flags/canada-flag.png'),
  "Australia": require('assets/flags/australia-flag.png'),
  "Spain": require('assets/flags/spain-flag.png'),
  "China": require('assets/flags/china-flag.png'),
  "Saudi Arabia": require('assets/flags/saudi-arabia-flag.png'),
  "Poland": require('assets/flags/poland-flag.png'),
  "Portugal": require('assets/flags/portugal-flag.png'),
  "India": require('assets/flags/india-flag.png'),
  "Russia": require('assets/flags/russia-flag.png'),
  "Mexico": require('assets/flags/mexico-flag.png'),
  "Netherlands": require('assets/flags/netherlands-flag.png'),
  "Italy": require('assets/flags/italy-flag.png'),
  "Turkey": require('assets/flags/turkey-flag.png'),
  "Brazil": require('assets/flags/brazil-flag.png'),
  "UAE": require('assets/flags/united-arab-emirates-flag.png'),
  "Switzerland": require('assets/flags/switzerland-flag.png'),
  "Denmark": require('assets/flags/denmark-flag.png'),
  "Singapore": require('assets/flags/singapore-flag.png'),
  "Romania": require('assets/flags/romania-flag.png'),
  "Greece": require('assets/flags/greece-flag.png'),
  "Belgium": require('assets/flags/belgium-flag.png'),
  "Ukraine": require('assets/flags/ukraine-flag.png'),
  "Vietnam": require('assets/flags/vietnam-flag.png'),
  "Czech Republic": require('assets/flags/czech-republic-flag.png'),
  "New Zealand": require('assets/flags/new-zealand-flag.png'),
  "Norway": require('assets/flags/norway-flag.png'),
  "Israel": require('assets/flags/israel-flag.png'),
  "Sweden": require('assets/flags/sweden-flag.png'),
  "Thailand": require('assets/flags/thailand-flag.png'),
  "Hungary": require('assets/flags/hungary-flag.png'),
  "Indonesia": require('assets/flags/indonesia-flag.png'),
  "Austria": require('assets/flags/austria-flag.png'),
  "Palestine": require('assets/flags/palestine-flag.png'),
  "Finland": require('assets/flags/finland-flag.png'),
  "Slovakia": require('assets/flags/slovakia-flag.png'),
  "Pakistan": require('assets/flags/pakistan-flag.png'),
  "Serbia": require('assets/flags/serbia-flag.png'),
  "Egypt": require('assets/flags/egypt-flag.png'),
  "Ireland": require('assets/flags/ireland-flag.png'),
  "England": require('assets/flags/england-flag.png'),
  "Chile": require('assets/flags/chile-flag.png'),
  "Croatia": require('assets/flags/croatia-flag.png'),
  "Argentina": require('assets/flags/argentina-flag.png'),
  "South Africa": require('assets/flags/south-africa-flag.png'),
  "Morocco": require('assets/flags/morocco-flag.png'),
  "Georgia": require('assets/flags/georgia-flag.png'),
  "Colombia": require('assets/flags/colombia-flag.png'),
  "Qatar": require('assets/flags/qatar-flag.png'),
  "Bulgaria": require('assets/flags/bulgaria-flag.png'),
  "Albania": require('assets/flags/albania-flag.png'),
  "Bangladesh": require('assets/flags/bangladesh-flag.png'),
  "Philippines": require('assets/flags/philiphines-flag.png'),
  "Scotland": require('assets/flags/scotland-flag.png'),
  "Algeria": require('assets/flags/algeria-flag.png'),
  "Azerbaijan": require('assets/flags/azerbaijan-flag.png'),
  "Kazakhstan": require('assets/flags/kazakhstan-flag.png'),
  "Lithuania": require('assets/flags/lithuania-flag.png'),
  "Nigeria": require('assets/flags/nigeria-flag.png'),
  "Estonia": require('assets/flags/estonia-flag.png'),
  "Montenegro": require('assets/flags/montenegro-flag.png'),
  "Peru": require('assets/flags/peru-flag.png'),
  "Jamaica": require('assets/flags/jamaica-flag.png'),
  "Malta": require('assets/flags/malta-flag.png'),
  "Uruguay": require('assets/flags/uruguay-flag.png'),
  "Iceland": require('assets/flags/iceland-flag.png'),
  "Bahrain": require('assets/flags/bahrain-flag.png'),
  "Luxembourg": require('assets/flags/luxembourg-flag.png'),
  "Costa Rica": require('assets/flags/costa-rica-flag.png'),
  "Puerto Rico": require('assets/flags/puerto-rico-flag.png'),
  "Jordan": require('assets/flags/jordan-flag.png'),
  "Kuwait": require('assets/flags/kuwait-flag.png'),
  "Venezuela": require('assets/flags/venezuela-flag.png'),
  "Ghana": require('assets/flags/ghana-flag.png'),
  "Tunisia": require('assets/flags/tunusia-flag.png'),
  "Nepal": require('assets/flags/nepal-flag.png'),
  "Ivory Coast": require('assets/flags/ivory-coast-flag.png'),
  "Macedonia": require('assets/flags/macedonia-flag.png'),
  "Kyrgyzstan": require('assets/flags/kyrgyzstan-flag.png'),
  "Uzbekistan": require('assets/flags/uzbekistan-flag.png'),
  "Libya": require('assets/flags/libya-flag.png'),
  "Bosnia": require('assets/flags/bosnia-flag.png'),
  "Iran": require('assets/flags/iran-flag.png'),
  "Kosovo": require('assets/flags/kosovo-flag.png'),
  "Mongolia": require('assets/flags/mongolia-flag.png'),
  "Syria": require('assets/flags/syria-flag.png'),
  "Tanzania": require('assets/flags/tanzania-flag.png'),
  "Malaysia": require('assets/flags/malaysia-flag.png'),
  "Paraguay": require('assets/flags/paraguay-flag.png'),
  "Monaco": require('assets/flags/monaco-flag.png'),
  "Senegal": require('assets/flags/senegal-flag.png'),
  "Somalia": require('assets/flags/somalia-flag.png'),
  "Dominican Republic": require('assets/flags/dominican-republic-flag.png'),
  "Cameroon": require('assets/flags/cameroon-flag.png'),
  "Republic of Congo": require('assets/flags/republic-of-congo-flag.png'),
  "Guatemala": require('assets/flags/guatemala-flag.png'),
  "Sudan": require('assets/flags/sudan-flag.png'),
  "Cuba": require('assets/flags/cuba-flag.png'),
  "Tajikistan": require('assets/flags/tajikistan-flag.png'),
  "Laos": require('assets/flags/laos-flag.png'),
  "Honduras": require('assets/flags/honduras-flag.png'),
  "Ethiopia": require('assets/flags/ethiopia-flag.png'),
  "Yemen": require('assets/flags/yemen-flag.png'),
  "Guinea": require('assets/flags/guinea-flag.png'),
  "Slovenia": require('assets/flags/slovenia-flag.png'), 
  "Burkina Faso": require('assets/flags/burkina-faso-flag.png'),
  "Bahamas": require('assets/flags/bahamas-flag.png'),
  "North Korea": require('assets/flags/north-korea-flag.png'),
  "Turkmenistan": require('assets/flags/turkmenistan-flag.png'),
  "Mauritius": require('assets/flags/mauritius-flag.png'),
  "Gambia": require('assets/flags/gambia-flag.png'),
  "Niger": require('assets/flags/niger-flag.png'),
  "Trinidad and Tobago": require('assets/flags/trinidad-and-tobago-flag.png'),
  "Sierra Leone": require('assets/flags/sierra-leone-flag.png'),
  "Benin": require('assets/flags/benin-flag.png'),
  "South Sudan": require('assets/flags/south-sudan-flag.png'),
  "Togo": require('assets/flags/togo-flag.png'),
  "Mauritania": require('assets/flags/mauritania-flag.png'),
  "Madagascar": require('assets/flags/madagascar-flag.png'),
  "Saint Vincent and the Grenadines": require('assets/flags/saint-vincent-and-the-grenadines-flag.png'),
  "Suriname": require('assets/flags/suriname-flag.png'),
  "Faroe Islands": require('assets/flags/faroe-islands-flag.png'),
  "Greenland": require('assets/flags/greenland-flag.png'),
  "Burundi": require('assets/flags/burundi-flag.png'),
  "Guyana": require('assets/flags/guyana-flag.png'),
  "French Guiana": require('assets/flags/french-guiana-flag.png'),
  "Tonga": require('assets/flags/tonga-flag.png'),
  "Central African Republic": require('assets/flags/central-african-republic-flag.png'),
  "Djibouti": require('assets/flags/djibouti-flag.png')
};

export default countryFlags;
