name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          lfs: true

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Create a .env file using GitHub Secrets
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_SERVER_URL=${{ vars.NEXT_PUBLIC_SERVER_URL }}" > .env

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Create CNAME file
        run: echo "website.fcde.app" > out/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_TOKEN }}
          publish_dir: ./out
